"""
OIL-003: Macro Events for Crude Oil
Events: OPEC meetings, Gulf hurricanes, major geopolitical events
"""
import pandas as pd, numpy as np
from scipy import stats
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

DATA_DIR = Path('data/oil'); REPORTS_DIR = Path('reports/oil')
REPORTS_DIR.mkdir(parents=True, exist_ok=True)
df = pd.read_csv(DATA_DIR / 'CLF_cleaned.csv', parse_dates=['Date'], index_col='Date')
close = df['Close'].dropna(); ret = close.pct_change().dropna()

report = []
report.append("# OIL-003: Macro Events for Crude Oil")
report.append("")

# Event 1: Major Hurricane seasons (Jun-Nov)
print("--- Hurricane Season ---")
report.append("## A. Hurricane Season (Jun-Nov)")
report.append("")
hurricane = ret[(ret.index.month >= 6) & (ret.index.month <= 11)]
non_hurricane = ret[~((ret.index.month >= 6) & (ret.index.month <= 11))]
for label, data in [('Hurricane Season', hurricane), ('Non-Hurricane', non_hurricane)]:
    n, m = len(data), data.mean()*100; wr = (data>0).mean()*100
    pos = data[data>0].sum(); neg = abs(data[data<0].sum())
    pf = pos/neg if neg>0 else np.inf; sh = data.mean()/data.std()*np.sqrt(252) if data.std()>0 else 0
    _, p = stats.ttest_1samp(data, 0); report.append(f"| {label} | {n} | {m:.4f}% | {wr:.1f}% | {pf:.4f} | {sh:.4f} | {p:.4e} |")
report.append("")

# Event 2: End of driving season (Sep/Oct typically bearish for oil)
print("--- Driving Season ---")
report.append("## B. Driving Season Transition")
report.append("")
for start_m, end_m, label in [(5,5,'May Start'), (9,9,'Sep End'), (4,4,'Pre-Season'), (10,10,'Post-Season')]:
    r = ret[ret.index.month == start_m]
    n, m = len(r), r.mean()*100; wr = (r>0).mean()*100
    pos = r[r>0].sum(); neg = abs(r[r<0].sum())
    pf = pos/neg if neg>0 else np.inf; _, p = stats.ttest_1samp(r, 0)
    report.append(f"| {label} | {n} | {m:.4f}% | {wr:.1f}% | {pf:.4f} | {p:.4e} |")
report.append("")

# Event 3: NFP / Macro by decade
print("--- Macro Regime by Decade ---")
report.append("## C. Macro Regime by Decade")
report.append("")
for start, end, label in [('2000','2007','2000-2007 Pre-Shale'), ('2008','2014','2008-2014 Volatile'), ('2015','2019','2015-2019 Shale Boom'), ('2020','2022','2020-2022 COVID+War'), ('2023','2026','2023-2026 Post-COVID')]:
    r = ret.loc[start:end] if end in ret.index or start in ret.index else ret[ (ret.index >= start) & (ret.index <= end)]
    if len(r) < 10: continue
    n, m = len(r), r.mean()*100; wr = (r>0).mean()*100; _, p = stats.ttest_1samp(r, 0)
    report.append(f"| {label} | {n} | {m:.4f}% | {wr:.1f}% | p={p:.4e} |")
report.append("")

# Event 4: Key historical crash events
print("--- Known Crash Events ---")
report.append("## D. Known Crash Events (Post-Event Returns)")
events = {
    'Gulf War 1990': '1990-08-02', 'Asian Crisis 1997': '1997-07-02',
    '9/11 2001': '2001-09-11', 'Iraq War 2003': '2003-03-20',
    'GFC 2008': '2008-09-15', 'Arab Spring 2011': '2011-01-25',
    'Shale Crash 2014': '2014-11-27', 'COVID Crash 2020': '2020-03-09',
    'Russia-Saudi 2020': '2020-03-06', 'Ukraine 2022': '2022-02-24',
}
for label, date_str in events.items():
    try:
        d = pd.Timestamp(date_str)
        mask = ret.index >= d
        if mask.any():
            after5 = ret.loc[d:].iloc[1:6] if len(ret.loc[d:]) > 5 else ret.loc[d:].iloc[1:]
            if len(after5) > 2:
                m5 = after5.mean()*100; wr5 = (after5>0).mean()*100
                report.append(f"| {label}: 5d post | {m5:.2f}% | {wr5:.1f}% |")
            after20 = ret.loc[d:].iloc[1:21] if len(ret.loc[d:]) > 20 else ret.loc[d:].iloc[1:]
            if len(after20) > 5:
                m20 = after20.mean()*100; wr20 = (after20>0).mean()*100
                report.append(f"| {label}: 20d post | {m20:.2f}% | {wr20:.1f}% |")
    except: pass
report.append("")

report.append("---")
report.append("*Generated by research/oil/scripts/oil_003_macro_events.py*")
with open(REPORTS_DIR / 'OIL-003_Macro_Events.md', 'w') as f:
    f.write('\n'.join(report))
print("OIL-003 COMPLETE")
