"""
OIL-006: Intraday H1 Analysis for Crude Oil
"""
import pandas as pd, numpy as np
from scipy import stats
from pathlib import Path
import warnings, yfinance as yf
warnings.filterwarnings('ignore')

REPORTS_DIR = Path('reports/oil')
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

print("Downloading CL=F H1 data...")
cl = yf.Ticker('CL=F')
raw = cl.history(period='max', interval='1h')
if len(raw) == 0: print("No H1 data"); exit()
if hasattr(raw.index, 'tz') and raw.index.tz is not None: raw.index = raw.index.tz_localize(None)
close = raw['Close'].dropna(); ret = close.pct_change().dropna()
print(f"Loaded {len(raw):,} hourly bars ({raw.index[0]} to {raw.index[-1]})")

report = []
report.append("# OIL-006: Intraday H1 Analysis")
report.append(f"**Period:** {raw.index[0]} to {raw.index[-1]}")
report.append(f"**Obs:** {len(ret):,} hours")
report.append("")

# Sessions (Oil trades nearly 24h on CME Globex, but has defined pit hours)
sessions = {
    'Asia (0-8 UTC)': (0, 8), 'Europe (8-14 UTC)': (8, 14),
    'US Pit (14-21 UTC)': (14, 21), 'US Afternoon (21-0 UTC)': (21, 24),
}
report.append("## A. Session Effect")
report.append("")
report.append("| Session | Hours (UTC) | N | Mean Ret% | WR% | PF | Sharpe | P |")
report.append("|---------|-------------|---|-----------|-----|----|--------|---|")
for sname, (sh, eh) in sessions.items():
    mask = (ret.index.hour >= sh) & (ret.index.hour < eh) if eh > sh else (ret.index.hour >= sh) | (ret.index.hour < eh)
    r2 = ret[mask]; n = len(r2)
    m = r2.mean()*100; wr = (r2>0).mean()*100; sp = r2.mean()/r2.std()*np.sqrt(365*24) if r2.std()>0 else 0
    pos = r2[r2>0].sum(); neg = abs(r2[r2<0].sum()); pf = pos/neg if neg>0 else np.inf
    _, p = stats.ttest_1samp(r2, 0)
    report.append(f"| {sname} | {sh}-{eh} | {n:,} | {m:.4f} | {wr:.1f} | {pf:.4f} | {sp:.4f} | {p:.4e} |")
report.append("")

report.append("## B. Hour of Day")
report.append("")
report.append("| Hour (UTC) | N | Mean Ret% | WR% | PF | Sharpe | P |")
report.append("|------------|---|-----------|-----|----|--------|---|")
for h in range(24):
    r2 = ret[ret.index.hour == h]; n = len(r2)
    if n < 10: continue
    m = r2.mean()*100; wr = (r2>0).mean()*100; sp = r2.mean()/r2.std()*np.sqrt(365*24) if r2.std()>0 else 0
    pos = r2[r2>0].sum(); neg = abs(r2[r2<0].sum()); pf = pos/neg if neg>0 else np.inf
    _, p = stats.ttest_1samp(r2, 0)
    report.append(f"| {h:02d}:00 | {n:,} | {m:.4f} | {wr:.1f} | {pf:.4f} | {sp:.4f} | {p:.4e} |")
report.append("")

report.append("## C. EIA Inventory Release (Wed 15:30 UTC)")
report.append("")
wed_1530 = ret[(ret.index.hour == 15) & (ret.index.minute == 30) & (ret.index.dayofweek == 2)]  # wed 15:30
other = ret[~((ret.index.hour == 15) & (ret.index.minute == 30) & (ret.index.dayofweek == 2))]
if len(wed_1530) > 5:
    m = wed_1530.mean()*100; wr = (wed_1530>0).mean()*100
    sp = wed_1530.mean()/wed_1530.std()*np.sqrt(365*24) if wed_1530.std()>0 else 0
    _, p = stats.ttest_1samp(wed_1530, 0)
    pos = wed_1530[wed_1530>0].sum(); neg = abs(wed_1530[wed_1530<0].sum()); pf = pos/neg if neg>0 else np.inf
    report.append(f"| EIA Wed 15:30 UTC | {len(wed_1530)} | {m:.4f} | {wr:.1f} | {pf:.4f} | {sp:.4f} | {p:.4e} |")
    report.append(f"| Non-EIA hours | {len(other):,} | | | | | |")
report.append("")

report.append("---")
report.append("*Generated by research/oil/scripts/oil_006_intraday.py*")
with open(REPORTS_DIR / 'OIL-006_Intraday_Analysis.md', 'w') as f:
    f.write('\n'.join(report))
print("OIL-006 COMPLETE")
