"""
OIL-002: Calendar Effects & Seasonality for Crude Oil
"""
import pandas as pd, numpy as np
from scipy import stats
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

DATA_DIR = Path('data/oil'); REPORTS_DIR = Path('reports/oil')
REPORTS_DIR.mkdir(parents=True, exist_ok=True)
df = pd.read_csv(DATA_DIR / 'CLF_cleaned.csv', parse_dates=['Date'], index_col='Date')
close = df['Close'].dropna(); ret = close.pct_change().dropna()

report = []
report.append("# OIL-002: Calendar Effects & Seasonality")
report.append(f"**Period:** {close.index[0].date()} to {close.index[-1].date()}")
report.append("")

print("--- Day of Week ---")
report.append("## A. Day of Week")
report.append("")
report.append("| Day | N | Mean Ret% | WR% | PF | Sharpe | T-test P |")
report.append("|-----|---|-----------|-----|----|--------|----------|")
for d in ['Monday','Tuesday','Wednesday','Thursday','Friday']:
    r = ret[ret.index.dayofweek == ['Monday','Tuesday','Wednesday','Thursday','Friday'].index(d)]
    if len(r) < 10: continue
    n, m = len(r), r.mean()*100
    wr = (r>0).mean()*100
    pos = r[r>0].sum(); neg = abs(r[r<0].sum())
    pf = pos/neg if neg>0 else np.inf
    sh = r.mean()/r.std()*np.sqrt(252) if r.std()>0 else 0
    _, p = stats.ttest_1samp(r, 0)
    pf_pass = "*" if pf > 1.30 else ""
    report.append(f"| {d} | {n} | {m:.4f} | {wr:.1f} | {pf:.4f} | {sh:.4f} | {p:.4e} |")
report.append("")

print("--- Month of Year ---")
report.append("## B. Month of Year")
report.append("")
report.append("| Month | N | Mean Ret% | WR% | PF | Sharpe | T-test P |")
report.append("|-------|---|-----------|-----|----|--------|----------|")
for m in range(1, 13):
    r = ret[ret.index.month == m]
    n, mn = len(r), r.mean()*100
    wr = (r>0).mean()*100
    pos = r[r>0].sum(); neg = abs(r[r<0].sum())
    pf = pos/neg if neg>0 else np.inf
    sh = r.mean()/r.std()*np.sqrt(12) if r.std()>0 else 0
    _, p = stats.ttest_1samp(r, 0)
    report.append(f"| {pd.Timestamp(2020,m,1).strftime('%B')} | {n} | {mn:.4f} | {wr:.1f} | {pf:.4f} | {sh:.4f} | {p:.4e} |")
report.append("")

print("--- Quarter ---")
report.append("## C. Quarter of Year")
report.append("")
report.append("| Quarter | N | Mean Ret% | WR% | PF | Sharpe | T-test P |")
report.append("|---------|---|-----------|-----|----|--------|----------|")
for q in [1,2,3,4]:
    r = ret[ret.index.quarter == q]
    n, mq = len(r), r.mean()*100
    wr = (r>0).mean()*100
    pos = r[r>0].sum(); neg = abs(r[r<0].sum())
    pf = pos/neg if neg>0 else np.inf
    sh = r.mean()/r.std()*np.sqrt(4) if r.std()>0 else 0
    _, p = stats.ttest_1samp(r, 0)
    report.append(f"| Q{q} | {n} | {mq:.4f} | {wr:.1f} | {pf:.4f} | {sh:.4f} | {p:.4e} |")
report.append("")

print("--- Summer/Winter Season ---")
report.append("## D. Driving Season vs Winter")
report.append("")
summer = ret[(ret.index.month >= 5) & (ret.index.month <= 9)]
winter = ret[(ret.index.month >= 11) | (ret.index.month <= 3)]
for label, data in [('Summer (May-Sep)', summer), ('Winter (Nov-Mar)', winter)]:
    n, m = len(data), data.mean()*100
    wr = (data>0).mean()*100
    pos = data[data>0].sum(); neg = abs(data[data<0].sum())
    pf = pos/neg if neg>0 else np.inf
    sh = data.mean()/data.std()*np.sqrt(252) if data.std()>0 else 0
    _, p = stats.ttest_1samp(data, 0)
    report.append(f"| {label} | {n} | {m:.4f} | {wr:.1f} | {pf:.4f} | {sh:.4f} | {p:.4e} |")
report.append("")

print("--- Preseason/Postseason Effects ---")
report.append("## E. Month Transition Effects")
report.append("")
for offset in [-5, -3, -1, 1, 3, 5]:
    for month in [5, 9, 11]:
        mask = (ret.index.month == month + offset) if offset > 0 else (ret.index.month == month + offset)
        if month + offset in range(1,13):
            r = ret[ret.index.month == month + offset]
            if offset < 0: r = ret[(ret.index.month == month) & (ret.index.day <= abs(offset))]
            elif offset > 0: r = ret[(ret.index.month == month) & (ret.index.day <= offset)]
            if len(r) > 5:
                n, m = len(r), r.mean()*100
                wr = (r>0).mean()*100
                pos = r[r>0].sum(); neg = abs(r[r<0].sum())
                pf = pos/neg if neg>0 else np.inf
                _, p = stats.ttest_1samp(r, 0)
                if pf > 1.30 and p < 0.05:
                    report.append(f"| {label} Month+{offset} | {n} | {m:.4f} | {wr:.1f} | {pf:.4f} | {p:.4e} |")
report.append("")

report.append("---")
report.append("*Generated by research/oil/scripts/oil_002_calendar.py*")
with open(REPORTS_DIR / 'OIL-002_Calendar_Effects.md', 'w') as f:
    f.write('\n'.join(report))
print("OIL-002 COMPLETE")
